---
- name: set chown -R mode on tomcat folder
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes

- name: set chmod +x on tomcat bin folder
  file:
    path: /opt/tomcat/bin
    owner: tomcat
    group: tomcat
    mode: '0755'
    state: directory
    recurse: yes