---
- name: copy tomcat.service to /etc/systemd/system
  ansible.builtin.copy:
    src: files/tomcat.service
    dest: /etc/systemd/system/tomcat.service
    user: root
    group: root
    mode: '0644'